CREATE TABLE TB_STUDENT2
(
  STUDENT_NO         VARCHAR2(10) NOT NULL,
  DEPARTMENT_NO      VARCHAR2(10) NOT NULL,
  STUDENT_NAME       VARCHAR2(40) NOT NULL,
  STUDENT_SSN        VARCHAR2(14),
  STUDENT_ADDRESS    VARCHAR2(200)
);

COMMENT ON COLUMN TB_STUDENT.STUDENT_NO  IS '학생 번호';
COMMENT ON COLUMN TB_STUDENT.DEPARTMENT_NO  IS '학과 번호';
COMMENT ON COLUMN TB_STUDENT.STUDENT_NAME  IS '학생 이름';
COMMENT ON COLUMN TB_STUDENT.STUDENT_SSN  IS '학생 주민번호';
COMMENT ON COLUMN TB_STUDENT.STUDENT_ADDRESS  IS '학생 주소';

ALTER TABLE TB_STUDENT
  ADD CONSTRAINT PK_STUDENT PRIMARY KEY (STUDENT_NO);
ALTER TABLE TB_STUDENT
  ADD CONSTRAINT FK_STUDENT_01 FOREIGN KEY (DEPARTMENT_NO)
  REFERENCES TB_DEPARTMENT (DEPARTMENT_NO);

INSERT INTO TB_STUDENT2 
VALUES (1, 'D1', '디자인', '050319-1234123', '서울시 동대문구');
INSERT INTO TB_STUDENT2 
VALUES (2, 'D2', '호재인', '060329-1235111', '서울시 종로구');
INSERT INTO TB_STUDENT2 
VALUES (3, 'J1', '집이야', '010519-1002322', '가고싶 보고싶');
INSERT INTO TB_STUDENT2 
VALUES (10, 'J1', '자바야', '040413-7665432', '화성시 어렵군구');
INSERT INTO TB_STUDENT2 
VALUES (11, 'J3', '슬픔이', '061111-1111111', '눈물이 흐르는군');

COMMIT;

SELECT * FROM TB_STUDENT2;